![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(0, 10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [15]:
matrix_45 = np.arange(1,21).reshape((4, 5))
matrix_45

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
matrix_45[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [19]:
matrix_45[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [21]:
matrix_45[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [25]:
matrix_45[:3:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [27]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

res_only_loro_1 = x[x == 'Loro']
res_only_loro_1

array(['Loro', 'Loro'], dtype='<U5')

In [34]:
bool_filter = np.array( x == 'Loro')
x[bool_filter]

array(['Loro', 'Loro'], dtype='<U5')

In [39]:
np.array([elem for elem in x if elem == 'Loro'])

array(['Loro', 'Loro'], dtype='<U4')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [72]:
np.random.rand((20)).reshape(2, 5, 2)

array([[[0.46321087, 0.364899  ],
        [0.14597861, 0.01600975],
        [0.25268388, 0.20108396],
        [0.23596917, 0.12769056],
        [0.34019792, 0.91803404]],

       [[0.19622354, 0.89518767],
        [0.54350712, 0.43143118],
        [0.03466707, 0.6885178 ],
        [0.26001494, 0.24655083],
        [0.36319028, 0.48683193]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [73]:
array_ceros = np.zeros(10, dtype=int)
print(array_ceros.nbytes)

array_ceros[3] = 1
print(array_ceros) 

80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [41]:
array_11 = np.arange(10,50)
array_11[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [118]:
def indices_no_cero(vector):
    return np.nonzero(vector)[0]

In [119]:
my_array = np.array([1, 2, 0, 0, 4, 0])
print(indices_no_cero(my_array))

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [74]:
np.random.seed(1234)
array_10x10 = np.random.randint(1, 100, size = (10, 10))
array_10x10

array([[48, 84, 39, 54, 77, 25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59, 93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39, 68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66, 76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14, 97, 13, 70, 96, 32],
       [90, 85, 46, 17, 42, 73, 57, 71, 57, 87],
       [45, 91, 84, 48, 50, 19, 86, 47, 99, 38],
       [39,  8, 68,  6, 48, 48, 16, 35, 11, 29],
       [ 5, 83, 90, 56, 79, 24, 51, 63, 56, 85],
       [ 1, 99, 91, 34, 22, 72, 69, 82, 53, 65]], dtype=int32)

In [75]:
print(array_10x10.min(), array_10x10.max())

1 99


In [76]:
print(np.min(array_10x10), np.max(array_10x10))

1 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [71]:
array_14 = np.random.randint(1,11, (30))
print(array_14)
print("La media es:", np.round(array_14.mean(), 2))

[ 3  6  6  9  3  5  5  2 10  6  4  9 10  9  9  8  4  6  4  9 10  4  7  6
  2  2  3  1  5  5]
La media es: 5.73


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [92]:
array_borde = np.ones((4, 4), dtype=int)
array_borde[1:-1, 1:-1] = 0

print(array_borde)


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [115]:
matriz_8x8 = np.zeros((8, 8), dtype=int)

matriz_8x8[::2, 1::2] = 1  # Filas pares, columnas impares
matriz_8x8[1::2, ::2] = 1  # Filas impares, columnas pares

print(matriz_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
patron = np.array([[0, 1],
                   [1, 0]])

matriz = np.tile(patron, (4, 4))
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
np.random.seed(1234)
matriz_18 = np.random.rand(5,5)
print(matriz_18)

# normalizar: valor - np.mean / np.std
# https://numpy.org/doc/2.2/reference/generated/numpy.mean.html
media = np.mean(matriz_18)
desviacion = np.std(matriz_18)
matriz_normalizada = (matriz_18 - media) / desviacion

print(matriz_normalizada)

[[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
 [0.27259261 0.27646426 0.80187218 0.95813935 0.87593263]
 [0.35781727 0.50099513 0.68346294 0.71270203 0.37025075]
 [0.56119619 0.50308317 0.01376845 0.77282662 0.88264119]
 [0.36488598 0.61539618 0.07538124 0.36882401 0.9331401 ]]
[[-1.34928699  0.27720685 -0.41926795  0.89386129  0.87352857]
 [-1.04304394 -1.0284193   0.95623919  1.54651765  1.23599271]
 [-0.72111911 -0.18028382  0.50896404  0.61941082 -0.67415328]
 [ 0.04711767 -0.17239653 -2.02071774  0.84652347  1.26133339]
 [-0.69441799  0.25185093 -1.78798362 -0.67954263  1.45208631]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [83]:
# 1. Crea una secuencia de números que vayan del 0 al 10
my_array = np.arange(11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
# 2. Crea un nuevo array, que parta del anterior, pero sustituya por el 
# valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
my_array_cp = my_array.copy()
my_array_cp[(my_array_cp >= 3) & (my_array_cp <= 8)] = -1
my_array_cp

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [89]:
# 3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8
my_array_cp2 = my_array.copy()
my_array_cp2[(my_array_cp2 >= 3) & (my_array_cp2 <= 8)] *= -1
my_array_cp2

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])